version: '3.2'

services:
    db:
      container_name: 'news_aggregator_database'
      image: mysql:5.7.10
      environment:
        MYSQL_DATABASE: 'news_aggregator'
        MYSQL_USER: 'admin'
        MYSQL_PASSWORD: 'nimda'
        MYSQL_ROOT_PASSWORD: 'toor'
      ports:
        - 5001:3306
      restart: always
    redis:
      container_name: 'news_aggregator_redis'
      image: redis:alpine
      ports:
        - 5002:6379
      restart: always
    app:
      container_name: 'news_aggregator'
      build: .
      links:
        - "db"
      depends_on:
        - "db"
      ports:
        - 5000:3000
      restart: always